[package]
name = "deduplicator"
version = "0.1.0"
authors = ["Rémi Dupré <r.dupre@qwant.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
geo = "0.12"
geo-geojson = "0.1"
lazy_static = "1.4"
num_cpus = "1.12"
rpostal = { git = "https://github.com/GuillaumeGomez/libpostal-rs.git" }
rprogress = { git = "https://github.com/remi-dupre/rprogress" }
rusqlite = "0.21"
structopt = { version = "0.3", default-features = false }
