dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8

before_install:
    - export CC="gcc-4.8"
    - git clone https://github.com/openvenues/libpostal
    - cd libpostal
    - ./bootstrap.sh
    - ./configure --datadir=$(pwd)/data
    - sudo make install
    - cd ..
    - sudo ldconfig

script:
  - rustc --version
  # Check for tools
  - cd tools && cargo check
  - cargo test
  - cd ..
  # Check for importers
  - cd importers/osm && cargo check
  - cargo test
  - cd ../..
  - cd importers/bano && cargo check
  - cargo test
  - cd ../..
  - cd importers/openaddresses && cargo check
  - cargo test
  - cd ../..
  # Check for deduplicator
  - cd deduplicator && cargo check
  - cargo test
  - cd ..
  # Run OSM importer and a complete deduplication
  - wget https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf
  - (cd importers/osm && cargo run --release -- ../../luxembourg-latest.osm.pbf)
  - (cd deduplicator && cargo run --release -- --osm ../luxembourg-latest.osm.pbf --output-csv luxembourg.csv)
