os: linux
dist: xenial
language: rust
rust:
  - nightly
  - stable
env:
  - TEST_TOOLS=1
  - TEST_IMPORTERS=1
  - TEST_DEDUPLICATOR=1
  - TEST_DEDUPLICATOR_COMPLETE=1

cache:
  cargo: true
  directories:
    # It appears that "ccache: true" is not working correctly.
    - /home/travis/.ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.8

env:
  - CARGO_TARGET_DIR=/home/travis/build/QwantResearch/addresses-importer/target

before_install:
  - if [ "$TEST_DEDUPLICATOR" == "1" ] || [ "$TEST_DEDUPLICATOR_COMPLETE" == "1" ]; then
      git clone https://github.com/openvenues/libpostal;
      cd libpostal;
      ./bootstrap.sh;
      ./configure --datadir=$(pwd)/data;
      CC="ccache gcc-4.8" ./configure --datadir=$(pwd)/data;
      sudo make install;
      cd ..;
      sudo ldconfig;
    fi
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TEST_TOOLS" == "1" ]; then
      echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    fi

script:
  - rustc --version
  # Check for tools
  - if [ "$TEST_TOOLS" == "1" ]; then
      cd tools && cargo check;
      cargo test;
      cd ..;
    fi
  # Check for importers
  - if [ "$TEST_IMPORTERS" == "1" ]; then
      cd importers/osm && cargo check;
      cargo test;
      cd ../..;
      cd importers/bano && cargo check;
      cargo test;
      cd ../..;
      cd importers/openaddresses && cargo check;
      cargo test;
      cd ../..;
    fi
  # Check for deduplicator
  - if [ "$TEST_DEDUPLICATOR" == "1" ]; then
      cd deduplicator && cargo check;
      cargo test;
      cd ..;
    fi
  # Run a complete deduplication
  - if [ "$TEST_DEDUPLICATOR_COMPLETE" == "1"]; then
      (cd deduplicator && cargo run -- --osm ../importers/osm/test-files/relations_ways.pbf --output-csv test.csv);
    fi
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TEST_TOOLS" == "1" ]; then
      docker build --label "org.label-schema.vcs-ref=$TRAVIS_COMMIT" -t qwantresearch/addresses-importer .;
      docker push qwantresearch/addresses-importer;
    fi
