dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8

before_install:
  - export CC="gcc-4.8"
  - git clone https://github.com/openvenues/libpostal
  - cd libpostal
  - ./bootstrap.sh
  - ./configure --datadir=$(pwd)/data
  - sudo make install
  - cd ..
  - sudo ldconfig
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    fi

script:
  - rustc --version
  # Check for tools
  - cd tools && cargo check
  - cargo test
  - cd ..
  # Check for importers
  - cd importers/osm && cargo check
  - cargo test
  - cd ../..
  - cd importers/bano && cargo check
  - cargo test
  - cd ../..
  - cd importers/openaddresses && cargo check
  - cargo test
  - cd ../..
  # Check for deduplicator
  - cd deduplicator && cargo check
  - cargo test
  - cd ..
  # Run a complete deduplication
  - (cd deduplicator && cargo run --release -- --osm ../importers/osm/test-files/relations_ways.pbf --output-csv test.csv)
  - if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --label "org.label-schema.vcs-ref=$TRAVIS_COMMIT" -t qwantresearch/addresses-importer .;
    docker push qwantresearch/addresses-importer;
    fi
