FROM debian:bullseye-slim

WORKDIR /srv/libpostal

ENV LIBPOSTAL_COMMIT "92f504c8c97cb9b97005bdca128c6299fdcbf4b0"

RUN apt-get update
RUN apt-get install -y git autoconf libtool build-essential curl libgeos-dev libsqlite3-dev

RUN git clone https://github.com/openvenues/libpostal libpostal \
    && cd libpostal \
    && git checkout ${LIBPOSTAL_COMMIT} \
    && ./bootstrap.sh \
    && ./configure --datadir=/srv/data \
    && make install -j \
    && cd .. \
    && rm -rf libpostal
