FROM debian:stretch-slim

WORKDIR /srv/libpostal

ENV LIBPOSTAL_COMMIT "95f31de3b25eaf0b23c8efd97b1243d9d690ba58"

RUN apt-get update
RUN apt-get install -y git autoconf libtool build-essential curl libgeos-dev libsqlite3-dev

RUN git clone https://github.com/openvenues/libpostal libpostal \
    && cd libpostal \
    && git checkout ${LIBPOSTAL_COMMIT} \
    && ./bootstrap.sh \
    && ./configure --datadir=/srv/data \
    && make install -j \
    && cd .. \
    && rm -rf libpostal
