[package]
name = "tools"
version = "0.1.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]
edition = "2021"

[dependencies]
rusqlite = "0.21"
serde = { version = "1.0", features = ["derive"] }
smartstring = "0.2"
time = { version = "0.2", features = ["std"] }

[lib]
name = "tools"
